language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a

branches:
  only:
  - travis-integration

android:
  licenses:
  - 'android-sdk-license-.+'
  - 'android-sdk-preview-license-.+'
  - 'intel-android-extra-license.+'
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.0
  - extra-android-m2repository


install: true

script:
  - ./gradlew assembleRelease

after_success:
  - bash <(echo OAUTH_ACCESS_TOKEN= $OAUTH_ACCESS_TOKEN > .deploy_key)
  - bash deployer.sh upload .travis.yml verifone/travis.log