language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a

branches:
  only:
  - travis-integration

android:
  licenses:
  - 'android-sdk-license-.+'
  - 'android-sdk-preview-license-.+'
  - 'build-tools-license-.+'
  - 'intel-android-extra-license.+'
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.2
  - extra-android-m2repository


install: true

script:
  - ./gradlew assembleRelease

after_success:
  - bash <(ls)
  - bash deployer.sh upload .travis.yml verifone/travis.log